import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/_layout/header";
import HeroBusiness from "@/components/_layout/hero-business";
import Footer from "@/components/_layout/footer";
import { FloatingNav } from "@/components/ui/floating-navbar";

const jakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  {
    name: "Home",
    link: "/",
  },
  {
    name: "About",
    link: "/about",
  },
  {
    name: "Contact",
    link: "/contact",
    
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${jakartaSans.className} min-h-screen bg-gradient-to-b from-[#071634] to-black`}
      >
        <Header />
        <FloatingNav navItems={navItems} />
        {children}
        <HeroBusiness />
        <Footer />
      </body>
    </html>
  );
}
